POST http://localhost:5073/breakfasts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMjA0YmY1YS04MWFlLTQzOGItOWVkNy05NTMzNWQyZTI1ZDIiLCJqdGkiOiJlNGI3ODdhZi02N2I0LTRhNGYtYTk2ZC1mNzVlZjFmNzk2MDAiLCJnaXZlbl9uYW1lIjoiV2lrdG9yIiwiZmFtaWx5X25hbWUiOiJLcnp5Y3prb3dza2kiLCJhdWQiOiJCdWJiZXJCcmVha2Zhc3QiLCJleHAiOjE3MzMxNjY2NTYsImlzcyI6IkJ1YmJlckJyZWFrZmFzdCJ9.jY2PAdB445Z_ku0hnM_WLV-PWaHvb8_pu1AE_2wXsuc

{
    "name": "Vegan Sunshine",
    "description": "12345 12345 12345 12345 12345 12345 12345",
    "startDateTime": "2022-04-08T08:00:00",
    "endDateTime": "2022-04-08T11:00:00",
    "savory": [
        "Oatmeal",
        "Avocado Toast",
        "Omelette",
        "Salad"
    ],
    "Sweet": [
        "Cookie"
    ]
}