GET http://localhost:5073/breakfasts/9FC20D94-3A07-4057-86AF-B534453F820A
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMjA0YmY1YS04MWFlLTQzOGItOWVkNy05NTMzNWQyZTI1ZDIiLCJqdGkiOiJlNGI3ODdhZi02N2I0LTRhNGYtYTk2ZC1mNzVlZjFmNzk2MDAiLCJnaXZlbl9uYW1lIjoiV2lrdG9yIiwiZmFtaWx5X25hbWUiOiJLcnp5Y3prb3dza2kiLCJhdWQiOiJCdWJiZXJCcmVha2Zhc3QiLCJleHAiOjE3MzMxNjY2NTYsImlzcyI6IkJ1YmJlckJyZWFrZmFzdCJ9.jY2PAdB445Z_ku0hnM_WLV-PWaHvb8_pu1AE_2wXsuc