GET http://localhost:5073/breakfasts/9FC20D94-3A07-4057-86AF-B534453F820A
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyN2RiNzQ3OS1hZmJiLTRkMTMtYjFhOC1jNDQ3OGY0YTkwMzYiLCJqdGkiOiIxOTA5N2MzNS1mYmVmLTRlNmQtOTIzNi02YTQ2M2Y1NGJmN2IiLCJnaXZlbl9uYW1lIjoiV2lrdG9yIiwiZmFtaWx5X25hbWUiOiJLcnp5Y3prb3dza2kiLCJhdWQiOiJCdWJiZXJCcmVha2Zhc3QiLCJleHAiOjE3MzE2MjA0NzksImlzcyI6IkJ1YmJlckJyZWFrZmFzdCJ9.FYeC_tIrz4R7XsxQap9GvqNLWV55yCVIj50Sv9Fc3Yc